apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaadin-flow-pre-24.2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaadin-flow-pre-24.2
  template:
    metadata:
      labels:
        app: vaadin-flow-pre-24.2
    spec:
      containers:
        - name: vaadin-flow-pre-24.2
          image: vaadin-flow-pre-24.2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: vaadin-flow-pre-24.2-balancer
spec:
  selector:
    app: vaadin-flow-pre-24.2
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
